name: Update translations from Transifex

on:
  schedule:
    - cron: '0 8 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update translations
      run: 'node scripts/transifex.js'
      env:
        TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
    - name: Create pull request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: i18n-patch
